student_palace.html
yelyseibocharov/ppos-ntu-khpi pull request #5
Opened 2024-10-21 20:06 UTC by Sofia-Kaliberda

2024-10-23 17:37 UTC, WilfredoN requested changes

2024-10-23 17:37 UTC, capynq commented on pages/student_palace/styles.css
> +    height: 65px;
Почему .5🥹

2024-10-23 17:37 UTC, capynq commented on pages/student_palace/styles.css
> +    line-height: 120%;
Пустые строки

2024-10-23 17:37 UTC, capynq commented on pages/student_palace/styles.css
> +    font-weight: 400;
Давайте использовать такие величины, а не проценты как у тебя чуть выше по коду (приведи все к одному виду)

2024-10-23 17:37 UTC, capynq commented on pages/student_palace/styles.css
> +    padding: 10px 30px;
Это можно пихнуть в * {}, нам нигде не нужны стандартные подчеркивания (да?)
(text-decoration:none;)

2024-10-23 20:52 UTC, WilfredoN requested changes

2024-10-23 20:52 UTC, WilfredoN commented on pages/student_palace/styles.css
> +    font-size: 100px;
font-size duplicate

2024-10-23 20:52 UTC, WilfredoN commented on pages/student_palace/styles.css
> +.text-detail {
у .text-detail по дизайну цвет текста #28373A

2024-10-24 10:53 UTC, Sofia-Kaliberda commented on pages/student_palace/styles.css
> +    height: 65px;
в плане height: 65px;? Извини. я не поняла🥹

2024-10-24 10:53 UTC, Sofia-Kaliberda commented on pages/student_palace/styles.css
> +    line-height: 120%;
буду удалять

2024-10-24 10:54 UTC, Sofia-Kaliberda commented on pages/student_palace/styles.css
> +    font-weight: 400;
оки, а какие именно?

2024-10-24 10:54 UTC, Sofia-Kaliberda commented on pages/student_palace/styles.css
> +.text-detail {
поняла, исправим

2024-10-25 11:39 UTC, WilfredoN commented on pages/student_palace/styles.css
> +    font-weight: 400;
line-height: 1.2; /* 120% в CSS */ 
пиши просто 
line-height: 1.2; 
на 134 строчке например, так же надо писать

2024-11-02 21:20 UTC, closed without merging