FIRST-PAGE-ELEMENTS
yelyseibocharov/ppos-ntu-khpi pull request #6
Opened 2024-10-23 00:10 UTC by pippsza

Сделал все нужные элементы первой страницы. (стрелочки доделаю)

2024-10-23 17:37 UTC, WilfredoN requested changes

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/global.css
> +.dont-copy-this {
Название понятней

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/global.css
> +  display: block;
? Оно что то меняет?

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/global.css
> +a {
Гуд вариант

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.css
> +  transition: 0.3s;
Мы должны указать к чему применяется анимация и тип анимации, иначе оно применится вообще ко всем свойствам элемента и при перезагрузке будет выглядеть не всегда красиво (https://developer.mozilla.org/en-US/docs/Web/CSS/transition)

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.css
> +  transition: 0.3s;
Например тут - transition: transform 0.3s ease-in-out;

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.css
> +  padding-top: 10%;
Паддинги в процентах 💀💀💀

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.css
> +  justify-content: end;
flex-end лучше может?

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.css
> +  right: 5%;
Этот процент будет разный при разных диагоналях, лучше пиксели может?

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.html
> +                height="30"
Пикселей?

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.html
> +                height="30"
Пикселей?

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-institut-teams.html
> +                height="30"
Пикселей?)

2024-10-23 17:37 UTC, capynq commented on pages/profkom-page/profkom-lead.html
> +      <img src="profkom-leader.png" alt="photo-of-profkom-lead" />
webp

2024-10-23 17:37 UTC, pippsza commented on pages/profkom-page/global.css
> +  display: block;
по-моему имг инлайновый по умолчанию

2024-10-23 17:40 UTC, pippsza commented on pages/profkom-page/profkom-institut-teams.css
> +  padding-top: 10%;
адаптив блять, адаптив🙄😘

2024-10-23 17:41 UTC, pippsza commented on pages/profkom-page/profkom-institut-teams.html
> +                height="30"
не ебу, я это у чела какого-то с нашего проекта скопипастил

2024-10-23 17:41 UTC, pippsza commented on pages/profkom-page/profkom-institut-teams.html
> +                height="30"
))))

2024-10-25 14:13 UTC, WilfredoN approved these changes

2024-10-25 14:13 UTC, merged